// sequence specs
#define NUMBER_OF_STEPS_PER_BEAT 4
#define NUMBER_OF_BARS 48
#define NUMBER_OF_BEATS_PER_BAR 4
#define NUMBER_OF_BEATS (NUMBER_OF_BARS*NUMBER_OF_BEATS_PER_BAR)
#define NUMBER_OF_STEPS (NUMBER_OF_STEPS_PER_BEAT*NUMBER_OF_BEATS)
#define NUMBER_OF_DRUMS 7
#define SEQUENCE_LENGTH (NUMBER_OF_STEPS*NUMBER_OF_DRUMS)

//sequence
const PROGMEM char sequence[SEQUENCE_LENGTH]  =
{
//Order of drums: snare, kick, hat, crash, tom1, ride, floor tom//
//Accents: HARD, MED, SOFT, NO_HIT

//bar 0, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 0, beat 3

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT,

//bar 0, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//BRIDGE//
//bar 1, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 1, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 1, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 1, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 2, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 2, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 2, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 2, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,  

//bar 3, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 3, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 3, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 3, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 4, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 4, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 4, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 4, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,  

//VERSE//
//bar 5, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 5, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 5, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 5, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 6, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 6, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 6, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 6, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 7, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 7, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 7, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 7, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 8, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 8, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 8, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 8, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 9, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 9, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 9, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 9, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 10, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 10, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 10, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 10, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 11, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 11, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 11, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 11, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 12, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 12, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 12, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT,
//bar 12, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//BRIDGE//
//bar 13, beat 1
NO_HIT, HARD, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 13, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 13, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 13, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 14, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 14, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 14, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 14, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,  

//bar 15, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 15, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 15, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 15, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 16, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 16, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 16, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 16, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
 
//CHORUS with double kick//
//bar 17, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 17, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 17, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 17, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 18, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 18, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 18, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 18, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 19, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 19, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 19, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 19, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 20, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 20, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 20, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 20, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 21, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 21, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 21, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 21, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 22, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 22, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 22, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 22, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 23, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 23, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 23, beat 3 //fill
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT,
//bar 23, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 24, beat 1
NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 24, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 24, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 24, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//VERSE//
//bar 25, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 25, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 25, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 25, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 26, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 26, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 26, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 26, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 27, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 27, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 27, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 27, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 28, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 28, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 28, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 28, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 29, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 29, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 29, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 29, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 30, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 30, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 30, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 30, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 31, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 31, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 31, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 31, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 32, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 32, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 32, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 32, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//BRIDGE//
//bar 33, beat 1
NO_HIT, HARD, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 33, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 33, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 33, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 34, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 34, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 34, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 34, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,  

//bar 35, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 35, beat 2
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 35, beat 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 35, beat 4
HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 36, beat 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 36, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 36, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 36, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

//CHORUS// ride
//bar 37, beat 1
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 37, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 37, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 37, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 38, beat 1
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 38, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 38, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 38, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 39, beat 1
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 39, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 39, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 39, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 40, beat 1
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 40, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 40, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 40, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 41, beat 1
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 41, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 41, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 41, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 42, beat 1
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 42, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 42, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, 
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 42, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 43, beat 1
NO_HIT, HARD, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 43, beat 2
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 43, beat 3
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, 
NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 43, beat 4
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, HARD,

//OUTRO//
//bar 44, beat 1
NO_HIT, HARD, NO_HIT, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 44, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 44, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 44, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 45, beat 1
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 45, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 45, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 45, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 46, beat 1
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 46, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 46, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 46, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

//bar 47, beat 1
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 47, beat 2
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 47, beat 3
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
//bar 47, beat 4
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT,
   
};

