#include "accents.h"
// sequence specs
#define NUMBER_OF_STEPS_PER_BEAT 4
#define NUMBER_OF_BARS 79
#define NUMBER_OF_BEATS_PER_BAR 4
#define NUMBER_OF_BEATS (NUMBER_OF_BARS*NUMBER_OF_BEATS_PER_BAR)
#define NUMBER_OF_STEPS (NUMBER_OF_STEPS_PER_BEAT*NUMBER_OF_BEATS)
#define NUMBER_OF_DRUMS 7
#define SEQUENCE_LENGTH (NUMBER_OF_STEPS*NUMBER_OF_DRUMS)
const PROGMEM int sequence[SEQUENCE_LENGTH]  =
{

// Bar: 0
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, NO_HIT, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 1
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 2
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 3
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 4
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 5
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 6
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 7
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 8
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 9
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 10
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 11
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 12
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 13
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 14
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 15
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 16
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 17
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 18
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 19
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 20
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 21
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 22
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 23
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 24
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 25
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 26
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 27
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 28
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 29
NO_HIT, HARD, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 30
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 31
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 32
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 33
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 34
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 35
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 36
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 37
NO_HIT, HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 38
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 39
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 40
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 41
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 42
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 43
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 44
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 45
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 46
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 47
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 48
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 49
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 50
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 51
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 52
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 53
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 54
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 55
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 56
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 57
NO_HIT, HARD, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 58
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 59
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 60
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 61
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 62
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 63
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 64
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, HARD, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, MED, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 65
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 66
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 67
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 68
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 69
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 70
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 71
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 72
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 73
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 74
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 75
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 76
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, HARD, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 77
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

HARD, NO_HIT, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, MED, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

// Bar: 78
NO_HIT, HARD, HARD, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 

NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, 
NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT, NO_HIT
};
